---@meta

---@class UABP_B1_Watts_Pounder_C : UCDAIAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Slot_3 FAnimNode_Slot
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_PowerIK_Ground FAnimNode_PowerIK_Ground
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_13 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_12 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_11 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_4 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_10 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_3 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_Root FAnimNode_Root
---@field ExecutingRunAndJumpAbility boolean
---@field Pawn ACDAICharacter
---@field DefaultMaxWalkSpeed float
---@field DeltaFocusRotation float
---@field TurnL boolean
---@field TurnR boolean
---@field CapturedRotationRate FRotator
---@field Run2JumpLock boolean
---@field Movement UCDAICharacterMovementComponent
---@field UpdateTurnInPlaceData boolean
UABP_B1_Watts_Pounder_C = {}

---@param AnimGraph FPoseLink
function UABP_B1_Watts_Pounder_C:AnimGraph(AnimGraph) end
function UABP_B1_Watts_Pounder_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_B1_Watts_Pounder_AnimGraphNode_TransitionResult_57A8A0AD48E96D6D8292F3823904D40C() end
function UABP_B1_Watts_Pounder_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_B1_Watts_Pounder_AnimGraphNode_PowerIK_Ground_8A22E0B249C6E58FC15B88A0848A23BF() end
function UABP_B1_Watts_Pounder_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_B1_Watts_Pounder_AnimGraphNode_SequencePlayer_5307E0B84FA9ABB13CEB85AC02E7828D() end
function UABP_B1_Watts_Pounder_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_B1_Watts_Pounder_AnimGraphNode_TransitionResult_9BFE07F4437ECEB4E0A8F782ECAE6095() end
function UABP_B1_Watts_Pounder_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_B1_Watts_Pounder_AnimGraphNode_TransitionResult_8E6042AF4AD14C92698E149A616002AB() end
function UABP_B1_Watts_Pounder_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_B1_Watts_Pounder_AnimGraphNode_SequencePlayer_BF61EBFB45772C6B7A8E02B5700E1AC7() end
function UABP_B1_Watts_Pounder_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_B1_Watts_Pounder_AnimGraphNode_TransitionResult_982EAD3440A4C493EDA13E9500324C8F() end
---@param DeltaTimeX float
function UABP_B1_Watts_Pounder_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UABP_B1_Watts_Pounder_C:AnimNotify_ExecuteJumpAttack() end
function UABP_B1_Watts_Pounder_C:AnimNotify_StartRun() end
function UABP_B1_Watts_Pounder_C:AnimNotify_EndStartRun() end
function UABP_B1_Watts_Pounder_C:AnimNotify_Start_Run2Jump() end
function UABP_B1_Watts_Pounder_C:AnimNotify_EnteredIdle() end
function UABP_B1_Watts_Pounder_C:AnimNotify_ExitIdleState() end
function UABP_B1_Watts_Pounder_C:OnStunStateChanged() end
---@param EntryPoint int32
function UABP_B1_Watts_Pounder_C:ExecuteUbergraph_ABP_B1_Watts_Pounder(EntryPoint) end


