---@meta

---@class UAnimBP_Detonator_C : UCDLeftArmActorAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_Slot FAnimNode_Slot
UAnimBP_Detonator_C = {}

---@param AnimGraph FPoseLink
function UAnimBP_Detonator_C:AnimGraph(AnimGraph) end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_6C6506A244C71841695F649FBDC263C8() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_674978BC4C8F0943EA8CC996A4137328() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_4764A8C74463ADD6801A9E801D9C7C58() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_75B561B24288619BEB8E9F83C7BE6D9E() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_E749EC3D4B115E46CC5799A150CE1E6C() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_3B38351E4508B3DAF2C1399F4C7D3408() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_E58944DE4E9CEC18C2229A82B3BB37DB() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_B3F5F744484B950BB088CF848D07F1BD() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_7D6594004CFD4C655E5E779E7116E8DE() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_5F1532734C81551CFBD8F3A5EE8A7490() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_99581AE241C77D27E300A0B964CC2B25() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_AB73A61C4288A773000FD7B335F6D4BE() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_F64CEDEA49E88A43860D2F88EC358391() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_AC44FD62486D40915F3DB491A1DB630B() end
function UAnimBP_Detonator_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Detonator_AnimGraphNode_TransitionResult_7A89435F4A167B7562FF249EC606E117() end
---@param EntryPoint int32
function UAnimBP_Detonator_C:ExecuteUbergraph_AnimBP_Detonator(EntryPoint) end


