---@meta

---@class UAnimBP_AssaultRifleV2_C : UCDWeaponAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
UAnimBP_AssaultRifleV2_C = {}

---@param AnimGraph FPoseLink
function UAnimBP_AssaultRifleV2_C:AnimGraph(AnimGraph) end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_6D0365094DA801B3CE280F943F0C9014() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_04237EA34F2E0FBED6D74FA9951BB74F() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_FDEB1CA44877E001C1E8CDA6215E3665() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_611AEA604494037A78BB049D5E6A315A() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_34817F004C7BB5732F32A197FF79875A() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_5F67673D444253570884ECB24BB00B46() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_1F55D0C44C776B63087C08918B4AA4D0() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_CBA6204041A9A793E64DE69EED9CAC9C() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_F51FFCED49896861082EEE93F7F962CB() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_F03E331D478885974CC8FF8BECB710EA() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_416D03EF4A34BB99498134A6B2497C6D() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_DAD0105447A9991BD22034BAE1B16EE2() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_E91E76CD4D13AE78860E72A8ED0FD7F8() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_5B3F6166491F6605E004B8BFA6FBFF1B() end
function UAnimBP_AssaultRifleV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_AssaultRifleV2_AnimGraphNode_TransitionResult_E952ACAB4E43DFE90FCA91947E7E1828() end
---@param EntryPoint int32
function UAnimBP_AssaultRifleV2_C:ExecuteUbergraph_AnimBP_AssaultRifleV2(EntryPoint) end


