---@meta

---@class UCountess_AnimBlueprint_C : UAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_ApplyAdditive FAnimNode_ApplyAdditive
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LegIK FAnimNode_LegIK
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_RotationOffsetBlendSpace FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field Speed float
---@field IsInAir boolean
---@field Pitch float
---@field Roll float
---@field Yaw float
---@field RotationLastTick FRotator
---@field YawDelta float
---@field IsAccelerating boolean
---@field Character ACountessPlayerCharacter_C
---@field isAttacking boolean
---@field CurrentAttack int32
---@field FullBody boolean
UCountess_AnimBlueprint_C = {}

---@param AnimGraph FPoseLink
function UCountess_AnimBlueprint_C:AnimGraph(AnimGraph) end
function UCountess_AnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Countess_AnimBlueprint_AnimGraphNode_BlendListByBool_5FA9E10845D70864E13AB3B908DB3614() end
function UCountess_AnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Countess_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_D90A92714BC7DA70E96FA891C892CCF5() end
---@param DeltaTimeX float
function UCountess_AnimBlueprint_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UCountess_AnimBlueprint_C:BlueprintInitializeAnimation() end
function UCountess_AnimBlueprint_C:Attacking_Event_0() end
function UCountess_AnimBlueprint_C:BlueprintBeginPlay() end
function UCountess_AnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_Countess_AnimBlueprint_AnimGraphNode_TransitionResult_4FF3B4A4456B104DD6A2F9AFC654640D() end
function UCountess_AnimBlueprint_C:AnimNotify_SaveAttack() end
function UCountess_AnimBlueprint_C:AnimNotify_ResetCombo() end
---@param EntryPoint int32
function UCountess_AnimBlueprint_C:ExecuteUbergraph_Countess_AnimBlueprint(EntryPoint) end


