---@meta

---@class UAnimBP_Taser_C : UCDTaserAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_Slot FAnimNode_Slot
UAnimBP_Taser_C = {}

---@param AnimGraph FPoseLink
function UAnimBP_Taser_C:AnimGraph(AnimGraph) end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_7420FB414DCF66274AF349BF4A6BA7F7() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_FA762F194A72210F543F338E6C152FC4() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_D2AC9B15410AC3B0E4EFF6BF47480B93() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_E938F51C46512BE026D528BBB77D3AFA() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_9940B151462C9A1D08A079831E3FBD7F() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_BC52C84349BCCA0B86F9C6BB7618927E() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_B2D0E1EA420F98F18EB23B9AA164B0DE() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_31EB365848B44972CD7BFEBDDC15AF91() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_B594875D4B86E20FAE7BC0AEF532073C() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_4899B0CB4C74660728EF8EBC25063558() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_CDB8B13D435B95691792DBA3031F1035() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_394C35C74A0007A0861E38AA42667D9E() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_4DD152B54C1206141ED9FABC84B2F99A() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_69E130E94B00E114C8288B8173F32975() end
function UAnimBP_Taser_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_Taser_AnimGraphNode_TransitionResult_500FC541477966126BAE7C9B3CB41832() end
---@param EntryPoint int32
function UAnimBP_Taser_C:ExecuteUbergraph_AnimBP_Taser(EntryPoint) end


