---@meta

---@class UAnimBP_FlakCannonV2_C : UCDWeaponAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_Slot FAnimNode_Slot
UAnimBP_FlakCannonV2_C = {}

---@param AnimGraph FPoseLink
function UAnimBP_FlakCannonV2_C:AnimGraph(AnimGraph) end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_5BBDE8644A57A62FBD602884B4FE15D9() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_342587134E67E1A5DC4A42BD911E1056() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_228D564D4E834060E19F07963E12004F() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_5F3AE9B9446607AEE64D6FB4A35DACFA() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_20C889EB4184F5C5E9384DA83C6BA24B() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_1D24C1754349ED68E3547CA95539EC30() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_969F2BF54153E8EE57870A9D934A8CA9() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_7FB91D3748DE4996CE7AB9B439BC2DCA() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_7AD3E94E441079F2AAE28387E2588AEB() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_817772B54B2E86156A3E5EBDFF57EAD1() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_C473FE7A4F3A1C6D5B1942B10F85D9AA() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_A305990C473649B5B8A87694BD73F310() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_BF417EBD41ECF4798AF45EB1257C297C() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_FA61B1294FC4EFB79A5CD4B558BB9BC4() end
function UAnimBP_FlakCannonV2_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_FlakCannonV2_AnimGraphNode_TransitionResult_AE4C17ED48C481DC76D82DAB0DF35029() end
---@param EntryPoint int32
function UAnimBP_FlakCannonV2_C:ExecuteUbergraph_AnimBP_FlakCannonV2(EntryPoint) end


