#ifndef UE4SS_SDK_BP_Boss_Watts_Thunderpunch_Projectile_ImpactEffect_Default_HPP
#define UE4SS_SDK_BP_Boss_Watts_Thunderpunch_Projectile_ImpactEffect_Default_HPP

class ABP_Boss_Watts_Thunderpunch_Projectile_ImpactEffect_Default_C : public ACDImpactVisualEffect
{
}; // Size: 0x250

#endif
