#ifndef UE4SS_SDK_BP_Boss_Watts_Thunderpunch_Projectile_ImpactEffectTemplate_HPP
#define UE4SS_SDK_BP_Boss_Watts_Thunderpunch_Projectile_ImpactEffectTemplate_HPP

class UBP_Boss_Watts_Thunderpunch_Projectile_ImpactEffectTemplate_C : public UCDImpactEffect
{
}; // Size: 0x48

#endif
