#ifndef UE4SS_SDK_BP_GrenadeLauncher_HotRod_ImpactEffectTemplate_Reverse_HPP
#define UE4SS_SDK_BP_GrenadeLauncher_HotRod_ImpactEffectTemplate_Reverse_HPP

class UBP_GrenadeLauncher_HotRod_ImpactEffectTemplate_Reverse_C : public UCDImpactEffect
{
}; // Size: 0x48

#endif
