#ifndef UE4SS_SDK_BP_GrenadeLauncher_HotRod_ImpactEffect_Default_Reverse_HPP
#define UE4SS_SDK_BP_GrenadeLauncher_HotRod_ImpactEffect_Default_Reverse_HPP

class ABP_GrenadeLauncher_HotRod_ImpactEffect_Default_Reverse_C : public ACDImpactVisualEffect
{
}; // Size: 0x250

#endif
