#ifndef UE4SS_SDK_BP_RocketLauncher_Rocket_ExplosionTemplate_Electric_HPP
#define UE4SS_SDK_BP_RocketLauncher_Rocket_ExplosionTemplate_Electric_HPP

class ABP_RocketLauncher_Rocket_ExplosionTemplate_Electric_C : public ACDExplosionVisualEffect
{
}; // Size: 0x260

#endif
